server:
  port: 8888
spring:
  application:
    name: ms-config-server

# Conexion via git
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 10000
        max-attempts: 20
      server:
        git:
          # order: 2
          default-label: ${GIT_BRANCH:main}
          uri: ${GIT:git@github.com:D4rk61/ms-config-server.git}
          # username:
          # password:
          ignore-local-ssh-settings: true
          # Configuracion del ssh conexion mas segura
          passphrase: ${GIT_PASSPHRASE:12345}
          private-key: |
                      -----BEGIN EC PRIVATE KEY-----
                      Proc-Type: 4,ENCRYPTED
                      DEK-Info: AES-128-CBC,E660FC19B6A9A3DACF879C8272F66AC4
  
                      Pwv/SuYgn8d1V3WeKYDurIFNScURVeOLsLTusZ9+oIJ2lZzp4tscT06qQw+TLShg
                      Y9gGsaAMtL+gtI6qfVeoMNAX3ehNIcxc9eeSTB+/XgzrFtmn3kvy1Exzk4/v/3TD
                      DY38nrOJtJUgT3HAvQU4ESsUnFJMBDXwTuGUuC2WQ1KRkR7/MKb3w7nVpEuzPn+K
                      uHRdbN5eEoB4eWtNOSXoa+dPNEWX5XmJCAKf+mgJF4cPSMJhPu2pHMisAQ8tsdYg
                      swHc/fJLdnb4MFpJHXwaiBFPcQeatcqQmEImiwQhBYE=
                      -----END EC PRIVATE KEY-----
  security:
    user:
      # A futuro configurarlo como variables de entorno
      name: ${CONFIG_SERVER_USERNAME:admin}
      password: ${CONFIG_SERVER_PASSWORD:admin}